controller_list:  
 - name: ur_arm_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
 - name: ur_gripper_controller
   action_ns: gripper_action
   type: GripperCommand
   default: true
   parallel: true
   joints:
    - robotiq_85_left_knuckle_joint
