# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - AJOINT
    - BJOINT
    - CJOINT
    - DJOINT
  sim_control_mode: 0  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_controller:
  type: joint_state_controller/JointStateController
  joints:
    - AJOINT
    - BJOINT
    - CJOINT
    - DJOINT
  gains:
    AJOINT:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    BJOINT:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    CJOINT:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    DJOINT:
      p: 100
      d: 1
      i: 1
      i_clamp: 1